### ISSUE TITLE
Login failed as user exception

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/gooddata-extractor#2]
This should be a user exception
```
GoodData login failed
#0 /code/vendor/keboola/gooddata-php-client/src/Keboola/GoodData/Client.php(423): Keboola\GoodData\Exception::loginError(Object(Keboola\GoodData\Exception))
#1 /code/src/Keboola/GoodDataExtractor/Extractor.php(21): Keboola\GoodData\Client->login('***', '***')
#2 /code/src/run.php(74): Keboola\GoodDataExtractor\Extractor->__construct(Object(Keboola\GoodData\Client), '***', '***', '/data/out/table...')
#3 {main}
```
https://connection.keboola.com/admin/utils/logs?file=2017/02/20/08/2017-02-20-08-49-38-58aa9f92924d8-exception

**Comment by odinuv** [comment]
dneska znovu 2060cd8c3922c92df6b0ea46d63a4e96

**Comment by ondrejhlavacek** [comment]
https://keboola.slack.com/archives/C09U3R1J4/p1560491156000700

**Comment by Halama** [comment]
Minulý týden taky párkrát https://keboola.slack.com/archives/C09U3R1J4/p1563971205006600
